version: '3'

services:
    mule:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: mule_server
        ports:
          - '80:8081'
          - '8080:8080'
          - '443:443'
        networks:
          - net
        volumes: 
          - ./apps:/opt/mule/apps
#          - ./logs:/opt/mule/logs

networks:
  net:
    driver: bridge

volumes:
    apps:
#    logs:
